export const JWT_TOKEN_FETCHING = 'JWT_TOKEN_FETCHING'
export const JWT_TOKEN_FETCHING_SUCCESS = 'JWT_TOKEN_FETCHING_SUCCESS'

export const BOARD_GAME_FETCHING = 'BOARD_GAME_FETCHING'
export const BOARD_GAME_FETCHING_SUCCESS = 'BOARD_GAME_FETCHING_SUCCESS'
export const BOARD_GAME_FETCHING_ERROR = 'BOARD_GAME_FETCHING_ERROR'
